
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/ui/Header/Header";
import ClientProvider from "@/components/ClientProvider";
import Sidebar from "@/components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-bg h-full w-full`}>
        <ThemeProvider attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange>
          <ClientProvider>
            <header className="sticky top-0">
              <Header />
            </header>
            <div className="flex overflow-hidde">
              <Sidebar />
              <main className="flex-1 overflow-y-auo">
                {children}
              </main>
            </div>
          </ClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
