export const commentData = [
    {
        kind: "youtube#commentThread",
        etag: "XuoeDp1r8w_9EYIi92q_E_6PLco",
        id: "UgwLt-QTP_DBTVg8yGF4AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "bbBAB2YF7Ptyvkc6L7cUMK1uATo",
                id: "UgwLt-QTP_DBTVg8yGF4AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay: "Ram ram 🙏🙏🙏",
                    textOriginal: "Ram ram 🙏🙏🙏",
                    authorDisplayName: "@Yogendrarjput8038",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/ytc/AIdro_kHj9nqpXnFDhEREGYNzCu-o1X56TCYliH-F5EEJWPvAANcainiV0EAKhWxMDpWdctw5Q=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl:
                        "http://www.youtube.com/@Yogendrarjput8038",
                    authorChannelId: {
                        value: "UCt00IvOYDZHixZUp1lBshPA",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 0,
                    publishedAt: "2024-09-06T18:28:46Z",
                    updatedAt: "2024-09-06T18:28:46Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "Bw-8EMkUg4Lq6NRI_eKo45KgeCQ",
        id: "UgyohfR_rrIDfBY8ZrF4AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "_e5u71-qtsOXBEy4miG-kJ3sBNA",
                id: "UgyohfR_rrIDfBY8ZrF4AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay: "Bhut achi h ❤❤❤",
                    textOriginal: "Bhut achi h ❤❤❤",
                    authorDisplayName: "@RavivermarBGMI",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/33M88gfi5KTm9rVR3QAK85klOAob8G2UZLOJQPM5H4jyCsvfI4vn0tn5l4KzE267tS2nGOAL=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl: "http://www.youtube.com/@RavivermarBGMI",
                    authorChannelId: {
                        value: "UC9hBLsRkv9SSZGVgwFDIKzg",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 0,
                    publishedAt: "2024-09-06T17:59:46Z",
                    updatedAt: "2024-09-06T17:59:46Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "Vd3Nvj_s3-pG-Tk-5jq9WLaodyQ",
        id: "UgxANW1rsUOa-R83BK94AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "7x2GvIQZ5_BSaZcgaz4-zGj_VR4",
                id: "UgxANW1rsUOa-R83BK94AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay: "Jay shree ram ❤",
                    textOriginal: "Jay shree ram ❤",
                    authorDisplayName: "@ChanchalSoni-xs5bb",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/ytc/AIdro_l54JuFkfz_MPuEzHjXdxfvxURY00Junn3arhXrUYET02NzrFzJeqJsa24OyzDDUvdakg=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl:
                        "http://www.youtube.com/@ChanchalSoni-xs5bb",
                    authorChannelId: {
                        value: "UC7XDpS36U0MQC1kMmvZNzZw",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 0,
                    publishedAt: "2024-09-06T17:40:15Z",
                    updatedAt: "2024-09-06T17:40:15Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "w2NMD6SjSTmWPebCNBgiw4IEhyE",
        id: "UgzbGlPpmQYVHijLeVh4AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "4gLVfWkg6bZcYju4-qCnJHYltkU",
                id: "UgzbGlPpmQYVHijLeVh4AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay: "Is part me ishq wala song kisko acha lga",
                    textOriginal: "Is part me ishq wala song kisko acha lga",
                    authorDisplayName: "@Comedykingbachche",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/mVRUBTltdzej2D0qbwMR9qy6YCypH4XhhFECXtMcqY4u1lGJYKZE0fmIBDnZFdRjCpAEk4fZIHk=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl:
                        "http://www.youtube.com/@Comedykingbachche",
                    authorChannelId: {
                        value: "UCXVbwAK2Dm_popIM0R74Bog",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 0,
                    publishedAt: "2024-09-06T17:24:27Z",
                    updatedAt: "2024-09-06T17:24:27Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "K3yAjjjCot9gqp90MZBQeqM0SE4",
        id: "Ugw75uSSdWjdxOC2jfp4AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "_XjZJh6ivDRcNX82fqESQDmvkGY",
                id: "Ugw75uSSdWjdxOC2jfp4AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay: "Ekdam bakbaas movie",
                    textOriginal: "Ekdam bakbaas movie",
                    authorDisplayName: "@MohammadIvran",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/Z51d1COYS0qHVF7Kq3IbyHWpFgLqG8Ci7KjGe5kITv3qKTv9QAhdpc-tA-hwtAjLthQmeZ94=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl: "http://www.youtube.com/@MohammadIvran",
                    authorChannelId: {
                        value: "UCKLYTVuDpqlJNrDumbsaVCQ",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 0,
                    publishedAt: "2024-09-06T17:16:14Z",
                    updatedAt: "2024-09-06T17:16:14Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "lOqjfVMFMY6DQhlB_8Pykg1Gzq0",
        id: "UgyGmnJPKxpxXoso4sJ4AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "GLND4Ti8lvPRxbn31AF2WzyrBuM",
                id: "UgyGmnJPKxpxXoso4sJ4AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay: "Ok",
                    textOriginal: "Ok",
                    authorDisplayName: "@Sunil-l3p",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/ytc/AIdro_nhZbF6KyS20xqBOxCQssP4k_DsHpTo75iLAxJBEBVoA29uk0fv5cejdx87SOdmd9rZAw=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl: "http://www.youtube.com/@Sunil-l3p",
                    authorChannelId: {
                        value: "UCL7QayedLuH2DIH8TrlEo8A",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 0,
                    publishedAt: "2024-09-06T17:11:31Z",
                    updatedAt: "2024-09-06T17:11:31Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "sOY-LTc4YQTZ4craYmMimjluB0I",
        id: "UgwwP4ELNCpugvgaRt54AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "pkkJ9ROtTMv-vsUnE38kYDwUmbE",
                id: "UgwwP4ELNCpugvgaRt54AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay:
                        "Uttar kumar sir ji meri ek baat mano aap apani movie free dish tv channel par provide karwa do please main aapka bahut bada fan hun ❤❤❤❤❤❤❤❤",
                    textOriginal:
                        "Uttar kumar sir ji meri ek baat mano aap apani movie free dish tv channel par provide karwa do please main aapka bahut bada fan hun ❤❤❤❤❤❤❤❤",
                    authorDisplayName: "@The_Jitendramotivation",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/cp7tC9Cy_gxvFaXJDZx5fyLwhvfTEGx-b_UFtQW4678kYCy0kGvDYZiSKHYHd_Z_c8_DsuY2=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl:
                        "http://www.youtube.com/@The_Jitendramotivation",
                    authorChannelId: {
                        value: "UCR9SRrImNR7uNGFyqQvoepQ",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 1,
                    publishedAt: "2024-09-06T16:45:32Z",
                    updatedAt: "2024-09-06T16:45:32Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "GTKHn9JZ-LGDZlxS0NNAspbVTA8",
        id: "Ugyg3AF0jDw-nXpUvlh4AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "3vydy0ZKIf4w4-QqfLY2cqr_r-Q",
                id: "Ugyg3AF0jDw-nXpUvlh4AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay:
                        "❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤",
                    textOriginal:
                        "❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤",
                    authorDisplayName: "@user-wc3me1re4f",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/ytc/AIdro_lA7jr0LZvBQFLmBc7jijnVjyoazsJEdCveoYk4bFvSLqy3mJRIVzhAwp7IKIkTOUTl9A=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl: "http://www.youtube.com/@user-wc3me1re4f",
                    authorChannelId: {
                        value: "UC4QWp2WAGSaGtjQoydv2FPQ",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 0,
                    publishedAt: "2024-09-06T15:45:22Z",
                    updatedAt: "2024-09-06T15:45:22Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "d1TwdCCKm0OQJLb09-csnn8ktxk",
        id: "Ugwadz1mQxRRKhxcHXd4AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "HGAFv_VQm1wG4cF69IVOAbNzd1E",
                id: "Ugwadz1mQxRRKhxcHXd4AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay:
                        "Bhai me rajsthani hu fir bi har movies godd lagti uttr Kumar ki",
                    textOriginal:
                        "Bhai me rajsthani hu fir bi har movies godd lagti uttr Kumar ki",
                    authorDisplayName: "@MaxMEENA-nw8ub",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/ytc/AIdro_lPAu5LcUW1h_9K92DDPIFAt7oKeKn1gaScOAfzdeLy0FyHMrhcwYmEo-u21qNz3kJRkA=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl: "http://www.youtube.com/@MaxMEENA-nw8ub",
                    authorChannelId: {
                        value: "UCDtKP3FVaYz67C4o2L1v6Ng",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 0,
                    publishedAt: "2024-09-06T15:27:47Z",
                    updatedAt: "2024-09-06T15:27:47Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "l4V3SyTKL2u9I2jm-YuzBMGwpQg",
        id: "UgzkskXyL9p9atz6uN54AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "q-lwzJ9k_2QHe8NZts0NANw0nJU",
                id: "UgzkskXyL9p9atz6uN54AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay:
                        "उत्तर कुमार जी आपकी तो शादी हो गई मूवी में हकीकत में ऐसा😂😂😂😂😂😂",
                    textOriginal:
                        "उत्तर कुमार जी आपकी तो शादी हो गई मूवी में हकीकत में ऐसा😂😂😂😂😂😂",
                    authorDisplayName: "@LaitSharma-x6w",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/ytc/AIdro_l7I9Z2ruLwb_8O5wqZX3BeggKDhG9XW1jritguKKq0ERDMHNocJbKZGdEYuVaEVLicvQ=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl: "http://www.youtube.com/@LaitSharma-x6w",
                    authorChannelId: {
                        value: "UC8Perbkh1cGWP9EeCw1hsGw",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 0,
                    publishedAt: "2024-09-06T14:30:04Z",
                    updatedAt: "2024-09-06T14:30:04Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "BwtGF9RJWMN-VCU9Ya0Sum_lfkY",
        id: "UgzjpysNGTa0aakh6MJ4AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "punb0dARQEdhHyhnyM_3YPcpOtA",
                id: "UgzjpysNGTa0aakh6MJ4AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay: "I love you uttar Kumar jii",
                    textOriginal: "I love you uttar Kumar jii",
                    authorDisplayName: "@mohindersingh5354",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/AcOkP_XjDNQfqDo-tMNxuiszaTq6YnB0ylF3-qPIO-GKAQ-bH20lj9lI1SNlZhoGZAmE6EjH=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl:
                        "http://www.youtube.com/@mohindersingh5354",
                    authorChannelId: {
                        value: "UC9R-SNjkdKOY7JVyXqVrMxA",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 1,
                    publishedAt: "2024-09-06T14:21:09Z",
                    updatedAt: "2024-09-06T14:21:09Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "79VR7GITBbIAK0jXCJ1coB4MKh8",
        id: "UgzwNPerWMZROotKJIR4AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "raNE4ZWJSK5xjKVFDj7qFP-BS-s",
                id: "UgzwNPerWMZROotKJIR4AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay: "Very good ❤❤❤",
                    textOriginal: "Very good ❤❤❤",
                    authorDisplayName: "@AamirAnsari-jh5nk",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/3FqKwpyML1WpANJDxmmx-lMJfdEgHfqlTaW1bYH7xDMmu6KB-9jiINGmPww0aZW_bia13L4=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl:
                        "http://www.youtube.com/@AamirAnsari-jh5nk",
                    authorChannelId: {
                        value: "UCNLqkcU6Djypg3jyLpD41fw",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 1,
                    publishedAt: "2024-09-06T12:41:44Z",
                    updatedAt: "2024-09-06T12:41:44Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "U_0ktUhtpx_piHoodSe_esNNEFo",
        id: "Ugy23UIwt8FkWhk8EMR4AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "SvCUfRhZ3hEF0LxZzr9O7BJbUTc",
                id: "Ugy23UIwt8FkWhk8EMR4AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay: "Uttar kumar bhai ki movie very nice",
                    textOriginal: "Uttar kumar bhai ki movie very nice",
                    authorDisplayName: "@JeetendraSingh-it9gh",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/TJ7y_5wgIT9pq5AbJObCILWbiTwuthF6iMTcI6eGCGh-LkXWhwnBQv1xy5HT4jXMgguAr3-KNg=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl:
                        "http://www.youtube.com/@JeetendraSingh-it9gh",
                    authorChannelId: {
                        value: "UCatV6QwEcq8pQiFDdoAo0RQ",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 1,
                    publishedAt: "2024-09-06T12:28:31Z",
                    updatedAt: "2024-09-06T12:28:31Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "c6DT3g_UQijHOHdUlnUq-E1bECY",
        id: "Ugzdnk6L6R4JWF7gJT54AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "DNgEl9Hw_deJt_z5vvQwJiv2NaU",
                id: "Ugzdnk6L6R4JWF7gJT54AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay: "😢❤❤",
                    textOriginal: "😢❤❤",
                    authorDisplayName: "@DevendraMouryaji",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/XV7IJ-JDv4u9My7zYTvsVtq1KYLxD8bzE3KqHYXxrDTLmV0a7GsBA6QUNvHEqKukF_p7PNTEfw=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl:
                        "http://www.youtube.com/@DevendraMouryaji",
                    authorChannelId: {
                        value: "UCd6Zz81M2k2ZnoMEAHNhz2A",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 1,
                    publishedAt: "2024-09-06T12:17:47Z",
                    updatedAt: "2024-09-06T12:17:47Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "gb1EEci1eln1a5yIpvbbZVy1Ieo",
        id: "UgyrCFnHuq4aKu-sOzh4AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "txTdZJGIJDsQr15CZi3WTRTOcLo",
                id: "UgyrCFnHuq4aKu-sOzh4AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay:
                        "Waw❤waw❤waw❤ बहुत सुन्दर प्रस्तुति दी है उत्तर कुमारजी🎉🎉 वेरी वेरी वेरी नाइस 😮😮",
                    textOriginal:
                        "Waw❤waw❤waw❤ बहुत सुन्दर प्रस्तुति दी है उत्तर कुमारजी🎉🎉 वेरी वेरी वेरी नाइस 😮😮",
                    authorDisplayName: "@Uttarakhandpaurigarhwal",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/ytc/AIdro_lLanP9P909h8I-3vNRnc0DAkkIZ-2G11LzJMqepuo3uWf_xQ0NFbk7x0sUSxzoyDss0g=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl:
                        "http://www.youtube.com/@Uttarakhandpaurigarhwal",
                    authorChannelId: {
                        value: "UCRdGvRP3z7KYw_Nb1sntKTw",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 1,
                    publishedAt: "2024-09-06T09:43:48Z",
                    updatedAt: "2024-09-06T09:43:48Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "XIMNYvgPimi_jjGfsuchbyg6RUA",
        id: "UgwaujPte1oNpQYnggV4AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "oTSj4uT-T72JSQ94uAUbfgWXN1s",
                id: "UgwaujPte1oNpQYnggV4AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay: "💥💥💥💥💯💯💯",
                    textOriginal: "💥💥💥💥💯💯💯",
                    authorDisplayName: "@akashthakur2499",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/ytc/AIdro_kz8s4NvReadZ9YDLIA1xue6BcJxlXzQjPx4ggiLQj3sQI=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl: "http://www.youtube.com/@akashthakur2499",
                    authorChannelId: {
                        value: "UCLDX-HtdYqwtfRHwQDzelfg",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 2,
                    publishedAt: "2024-09-06T09:31:35Z",
                    updatedAt: "2024-09-06T09:31:35Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "HLj755oU9Kc-JZwbbq41QpPU12k",
        id: "UgygbjSmplQ9CoVmw354AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "qV3V4RuvLV-9cDA7J6oNw7PmWQE",
                id: "UgygbjSmplQ9CoVmw354AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay: "Hindu like kare",
                    textOriginal: "Hindu like kare",
                    authorDisplayName: "@kapilsaini8938",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/ytc/AIdro_kvlWfpFiGDsOuWN8WC7fbTg_M3GnIyZoNdq97hjvUJDaKXfd4Br8mhKtbUbhXvgfORVQ=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl: "http://www.youtube.com/@kapilsaini8938",
                    authorChannelId: {
                        value: "UCMC3raHxDGzI48ZAEUub8cw",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 0,
                    publishedAt: "2024-09-06T08:53:31Z",
                    updatedAt: "2024-09-06T08:53:31Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "SycxIgojSh462roc9Ym_-OWw3NA",
        id: "UgzR6JzG6xTouf4WSF54AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "FC7xUrZbPSItjsXZu_IBpQooI-E",
                id: "UgzR6JzG6xTouf4WSF54AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay: "❤❤❤",
                    textOriginal: "❤❤❤",
                    authorDisplayName: "@VinayGijwal-rb1oe",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/eumT_bwMHP7blWGgTXs2zz3VIgsXES8F3l-aXbNPPvGVjaWYArpNIJDZys7S7blJ1-PFySKddQ=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl:
                        "http://www.youtube.com/@VinayGijwal-rb1oe",
                    authorChannelId: {
                        value: "UCd54A2VrF8JeH-5FnGnXV9A",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 1,
                    publishedAt: "2024-09-06T06:30:24Z",
                    updatedAt: "2024-09-06T06:30:24Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "M-oJxP7XEIj_VsRl8oZpVLKvRk0",
        id: "UgzAsE1kdRlm10Msa6p4AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "7JG9yiSRXXh0NWW-czEia4GIfEo",
                id: "UgzAsE1kdRlm10Msa6p4AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay: "Very Very nice movie",
                    textOriginal: "Very Very nice movie",
                    authorDisplayName: "@PkKumar-j1f",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/ytc/AIdro_l2m6xnQIkGIe085t1l3QKu9OLcA7ubGl9YcT6fJ4x_XnEE37zF6vFZuGyS8tIezkPGIA=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl: "http://www.youtube.com/@PkKumar-j1f",
                    authorChannelId: {
                        value: "UCXPyxvX2utKDGGlKpQ-SMpQ",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 1,
                    publishedAt: "2024-09-06T06:10:21Z",
                    updatedAt: "2024-09-06T06:10:21Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
    {
        kind: "youtube#commentThread",
        etag: "Z2ZqEW8yi936uu-1L1YJClL-P08",
        id: "UgwG_W_Vrmp2Xa8gSG94AaABAg",
        snippet: {
            channelId: "UCq_7HCsiy115mre6OBH_dAQ",
            videoId: "7KIH4BlQito",
            topLevelComment: {
                kind: "youtube#comment",
                etag: "B_mTyHKARY9LAf-8FBzTJmvhiz8",
                id: "UgwG_W_Vrmp2Xa8gSG94AaABAg",
                snippet: {
                    channelId: "UCq_7HCsiy115mre6OBH_dAQ",
                    videoId: "7KIH4BlQito",
                    textDisplay: "❤❤❤😂Hii",
                    textOriginal: "❤❤❤😂Hii",
                    authorDisplayName: "@vikkikumar5664",
                    authorProfileImageUrl:
                        "https://yt3.ggpht.com/2vM8-y73efHAgrZy8Ep6C2wUKf09A7b_OTSwbyX0f5-dxFF2BzUSv7C2QXF3jCk2DX1my6pS9w=s48-c-k-c0x00ffffff-no-rj",
                    authorChannelUrl: "http://www.youtube.com/@vikkikumar5664",
                    authorChannelId: {
                        value: "UC3xKK--ZPFCf1zB2H2-q_Ng",
                    },
                    canRate: true,
                    viewerRating: "none",
                    likeCount: 1,
                    publishedAt: "2024-09-06T05:49:27Z",
                    updatedAt: "2024-09-06T05:49:27Z",
                },
            },
            canReply: true,
            totalReplyCount: 0,
            isPublic: true,
        },
    },
]
